version: '3.8'

services:
  bot:
    build: .
    container_name: accounts_checker
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py